### ISSUE TITLE
Can't read Monero Elect keywords with "online mode"

### ISSUE THREAD

**Issue by lpiechowiak** [LedgerHQ/app-monero#105]
Hello. I have issue than I can't resolve from a long time. I have Ledger Nano X, newest firmware, everything installed as you describe in instruction, but I can't read election words in offline mode.
MacOS Catalina 10.15.7
Here is the log:

> $ PYTHONPATH=`pwd`/src  python3 -m ledger.monero.seedconv.py online

=============================================================
Monero Seed Converter v0.9. Copyright (c) Ledger SAS 20018.
Licensed under the Apache License, Version 2.0
=============================================================

* Select Language
   2 : English (English)
   3 : Esperanto (Esperanto)
   4 : Français (French)
   5 : Italiano (Italian)
   7 : Lobjan (Lobjan)
   8 : Português (Portuguese)
Enter the number corresponding to the language of your choice (2):
Open device...
Erase old key words...
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/poison/KRYPTO/app-monero-master-2/tools/python/src/ledger/monero/seedconv.py", line 356, in <module>
    get_online_seed(retrieve_language(True))
  File "/Users/poison/KRYPTO/app-monero-master-2/tools/python/src/ledger/monero/seedconv.py", line 303, in get_online_seed
    send_dict_chunk(dongle,lang['prefix_length'], chunk, start, cnt)
  File "/Users/poison/KRYPTO/app-monero-master-2/tools/python/src/ledger/monero/seedconv.py", line 276, in send_dict_chunk
    dongle.exchange(apdu)
  File "/Library/Python/3.7/site-packages/ledgerblue/comm.py", line 93, in exchange
    result = self.waitImpl.waitFirstResponse(timeout)
  File "/Library/Python/3.7/site-packages/ledgerblue/comm.py", line 152, in waitFirstResponse
    data = self.device.read(65)
  File "hid.pyx", line 200, in hid.device.read
OSError: read error
Load dictionnary...............................................................................................

----
And after this my Ledger is turning off and that's all folks.
Any hints? Any suggestions?

Is there any possiblity to publish binary for all ledger+monero users or it isn't so easy as I think?

Best regards.
Luke

**Comment by DevJackSmith** [comment]
Was able to replicate the same exact behavior/bug with Python 3.9.7, MacOs Monterey 12.4, and ledger nano x with latest firmware.

**Comment by DevJackSmith** [comment]
this is duplicate of #104 but I wish 104 had better title
