### ISSUE TITLE
Broken. UnicodeEncodeError: 'ascii' codec can't encode characters in position 7-10: ordinal not in range(128)

### ISSUE THREAD

**Issue by grigio** [LedgerHQ/app-monero#31]
Followed the instruction with also #24 and it still doesn't work

```
PYTHONPATH=`pwd`/src python3 -m ledger.monero.seedconv offline

=============================================================
Monero Seed Converter v0.9. Copyright (c) Ledger SAS 20018.
Licensed under the Apache License, Version 2.0
=============================================================
        
* Select Language
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/tools/python/src/ledger/monero/seedconv.py", line 359, in <module>
    get_offline_seed(retrieve_language(False))
  File "/app/tools/python/src/ledger/monero/seedconv.py", line 82, in retrieve_language
    print('  %2d : %s (%s)'%(i, l['language_name'], l['english_language_name']))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 7-10: ordinal not in range(128)
```

**Comment by grigio** [comment]
Just comment like `82` and it works

**Comment by grydz** [comment]
I've tested with Python 3.5 in a new virtualenv and I can't reproduce the issue.

Do you confirm you still have the problem?

**Comment by grydz** [comment]
I'm closing the issue.

Feel free to open a new one if you encounter the problem again.
