### ISSUE TITLE
Seed Recovery Fails

### ISSUE THREAD

**Issue by d-bischoff** [LedgerHQ/app-monero#97]
I am using a Ledger NanoX Firrmware 1.3 with Monero Ledger SAS Spec 1.0 App 1.7.7 installed, unlocked and in the Monero App.
My computer is running windows and running `py -m ledger.monero.seedconv.py online` as described in https://github.com/LedgerHQ/app-monero/tree/master/tools/python yields the following result.

```
=============================================================
Monero Seed Converter v0.9. Copyright (c) Ledger SAS 20018.
Licensed under the Apache License, Version 2.0
=============================================================

* Select Language
   2 : English (English)
   3 : Esperanto (Esperanto)
   4 : Français (French)
   5 : Italiano (Italian)
   7 : Lobjan (Lobjan)
   8 : Português (Portuguese)
Enter the number corresponding to the language of your choice (2): 2
Open device...
Erase old key words...
Traceback (most recent call last):
  File "C:\Users\Ich\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\Ich\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\Ich\projects\app-monero\tools\python\src\ledger\monero\seedconv.py", line 356, in <module>
    get_online_seed(retrieve_language(True))
  File "C:\Users\Ich\projects\app-monero\tools\python\src\ledger\monero\seedconv.py", line 287, in get_online_seed
    dongle.exchange(pack('>6B', 0x00, 0x28, 0x02, 0x00, 0x01, 0x00))
  File "C:\Users\Ich\AppData\Local\Programs\Python\Python39\lib\site-packages\ledgerblue\comm.py", line 145, in exchange
    raise CommException("Invalid status %04x (%s)" % (sw, possibleCause), sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 6e00 (Unexpected state of device: verify that the right application is opened?)
```

What are the pre-requisits I am missing?

**Comment by jonathancross** [comment]
Hi, can you try this again with the latest app installed and open?
